# Project info
site_name: IBM Cloud Satellite L3 Demonstration
site_description: IBM Cloud Satellite Sales Enablement Level 3 Demonstration
site_author: Andrew R. Jones (andrewj@us.ibm.com)
copyright: Copyright &copy; 2022 IBM

# Repository
repo_name: IBM/SalesEnablement-Satellite-L3
#repo_url: https://github.com/IBM/SalesEnablement-Satellite-L3/
#edit_uri: edit/master/docs
docs_dir: docs


nav:
  - Home: README.md
  - IBM Cloud Satellite overview:
    - 'Introduction': 'environment/01.01 Introduction.md'
    - 'Prerequisites': 'environment/01.02 Prerequisites.md'
    - 'Using the demonstration guide': 'environment/01.03 Using the demonstration guide.md'
    - 'What are IBM Cloud Satellite Locations': 'environment/02.01 What are Locations.md'
    - 'Watch: How to provision a Location in AWS': 'environment/02.02 Watch: How to provision a Location in AWS.md'
    - 'Demonstrate: How to provision a Location': 'environment/02.03 Demonstrate: How to provision a Location.md'
    - 'What are Links': 'environment/03.01 What are Links.md'
    - 'Using the IBM Cloud command line interfaces (CLIs)': 'environment/04.01 Using the IBM Cloud command line interfaces (CLIs).md'
    - 'Next steps': 'environment/05.01 Next steps.md'

  - Deploy an OpenShift application:
    - 'Introduction': 'deploy-application/01.01 Introduction.md'
    - 'The Food Delivery Application': 'deploy-application/01.02 The Food Delivery Application.md'
    - 'Demonstration flow': 'deploy-application/01.03 Demonstration flow.md'
    - 'Watch the demonstration': 'deploy-application/01.04 Watch the demonstration.md'
    - 'Create cluster groups': 'deploy-application/02.01 Create cluster groups.md'
    - 'Create a configuration': 'deploy-application/03.01 Create a configuration.md'
    - 'Create versions': 'deploy-application/03.02 Create versions.md'
    - 'Create subscriptions': 'deploy-application/03.03 Create subscriptions.md'
    - 'Verify the application is deployed': 'deploy-application/03.04 Verify the application is deployed.md'
    - 'Update the development and production frontends': 'deploy-application/04.01 Update the development and production frontends.md'
    - 'Perform a rollback': 'deploy-application/04.02 Perform a rollback.md'
    - 'Next steps': 'deploy-application/05.01 Next steps.md'

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.top
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

plugins:
    - search
    - macros

extra:
  generator: false

markdown_extensions:
  - sane_lists
  - pymdownx.details
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra:
  learningplan:
    name: "IBM Cloud Satellite Sales Level 3"
    url: "https://yourlearning/"
  tz_environment:
    name: "IBM Cloud Satellite - Sales Enablment L3"
    url: "https://techzone.ibm.com/my/reservations"
    uuid_label: "Demo-UUID"
  account: "2435442 - ITZ - Satellite"
  aws:
    location: aws-us-east-2
    host_ip: ip-10-0-1-114
    cluster_name: aws_os_cluster
    ingress: aws-os-cluster-222b3514854c2221251113b2b051506c-0000.upi.containers.appdomain.cloud
  ibm:
    cluster_name: ibmcloud-wdc-os
    ingress: ibmcloud-wdc-os-222b3514854c2221251113b2b051506c-0000.us-east.containers.appdomain.cloud
